{{- define "todosvc.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-svc.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-svc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.service.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-svc.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.service.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "todo-svc.fullname" . }}
      {{- with .Values.service.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
